language: python

python:
  - 3.5.2

addons:
  - postgresql: "9.6.4"

before_install:
  - export DATABASE_URL=postgres://postgres@localhost/travisdb

install:
  - pip install -r requirements.txt

env:
  - DJANGO=1.11.5

deploy:
  provider: heroku
  api_key:
    secure: E8izS1qhoHbn6E3P7hNzY/WzhsWtFRMsgVuES0kICdEIad2+L1L5ohwlKz++XCqvvIK6EIbctUk4QMp84b3Ak/8jdfzDo+XaabqUmc7bT/AEIVakRTh08G4zKxylI2RSHqavDyCfurdly3FxzLqnboQrfZQ5y+qLm6d1G5X2yLFcBbkoGfjiWiKnidHDP8qotH4ISIYkp9dNU5JU4OcIMUJITcaNB7obPM6VYHIimYAc/1PSYAOS8ANgPLX+9GBBHA3nFWDSb0Gv5YCRAvMPlrv5P4cncVEvN1IVBz+OMjNI4pbMyr9nb5fLzQnWIuVJkTkD47OENxRh4u78o+KwmKEgZvoeCGhl8+14Hggz/4odtfbJbKdL/E6iIeIWdxw5zra4cIddfHGhjLQf40eBs3QARHXh4dG4kCtxj6q6kgC4GSOka7KkMT4t8VGxO7Tc/TDzcOGFbEB3gkwRU13iZH+kJO37FGvFmyEScbYDL9ExVTEnbnF52Ed8Oe7E48pro1de73gR2dgU92oWPH5G1+3yYdtsQK1TiHPgwLM7A9BbiZqBrznGYRhWBV/xiPRLbZtf/Il8bRJSTPHRjsgmuHWlYW83a7Bt52DnfwzDQcze2/hwe0I4tPiHMjY0xkID7fnwELNsIs/BY+WuSMVJByAdFZnmdpn5t97izFHRKFM=
  app: meupetapidev
  strategy: git
  run:
    - python meupetapi/manage.py makemigrations api
    - python meupetapi/manage.py migrate
before_script: 
    - python meupetapi/manage.py makemigrations
    - python meupetapi/manage.py migrate
script: python meupetapi/manage.py test api
