language: python

python:
  - 3.5.2

addons:
  - postgresql: "9.6.4"

before_install:
  - export DATABASE_URL=postgres://postgres@localhost/travisdb

install:
  - pip install -r requirements.txt


# before_script:
#   - psql -c "CREATE DATABASE travisdb;" -U postgres
#   - python captaincook/manage.py migrate --noinput

env:
  - DJANGO=1.11.5

deploy:
  provider: heroku
  api_key:
    secure: sxJo8Z7vxfOiuXPvkMije9m1HBXOXDiotluDOPqTlaGgLXk+ssC9AyWEBe6IE157z/A+tWS4Q3Mkl7pXv0miwvfeIzNfoF82a2oHIa3Q626mvq64WuvOUwke1RUKXioEml6sr+k7M3kzR4Wzwt8TVivKYkzVcn233I00/6tRnyLMR0K5AiH/5u2azzix9ujvNWENSV7kWz6vCkePlC/jmqQQ+H9vtWxuhxd1s17FoA5ZeindPDk2rTDhBiulSx7Ykbk+lnsIkcpOojlceU7HkYsV0QP8C4svyFipJerzqNhf7ALDDlmzZPqM0ip4C2shQ15OlECCLPVf+Vcr4G4A/rajE8KqgIZCD8FuIyTZYP1vTZrfzILW0pBFGawisiArXjrTzqtm7qweQiU8RI/+PmgNXsuAZmj9bb7ScLHqc3bBcsWMdRQhehmE9Zie+lvf7zyEGRyjL5rWJKN54bsTCEt3c288VVk+Mk+crKTuHoNDz94bpftm8ap4AsZ1SDVpbJD+PlD7fTw+eHsUrqbtk/mcuxqtL6BiRyHBV965Ff9vHm8SNszG2om0rt8wiplGwTppSUiUxsYs4kGkgrim72vDcmKp5A/en7EFoHMxjEYR1302S2x4eLNKOGT1xn775QIhkahLYKRBTmFxY+vfQb4zSdKyf5JsNwW5SvZttRY=
  app: meupetapidev
  strategy: git
  run:
    - python meupetapidev/manage.py makemigrations api
    - python meupetapidev/manage.py migrate

script: python meupetapidev/manage.py test api
