# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primeiroNome', models.CharField(max_length=255)),
                ('segundoNome', models.CharField(max_length=255)),
                ('idade', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=30)),
                ('descricaoUsuario', models.TextField()),
                ('qtdPets', models.CharField(max_length=255)),
                ('tipousuario', models.ManyToManyField(to='api.TipoUsuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipousuario',
        ),
        migrations.AddField(
            model_name='passeador',
            name='descricaoUsuario',
            field=models.TextField(default='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passeador',
            name='senha',
            field=models.CharField(default='123', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passeador',
            name='tipousuario',
            field=models.ManyToManyField(to='api.TipoUsuario'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dono'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
