# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171011_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estaPasseando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='regiao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
