# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171016_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passeio',
            name='idRecorrencia',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Passeio'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='local',
            field=models.TextField(default='bla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passeio',
            name='origem',
            field=models.TextField(default='bla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passeio',
            name='passeador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passeio',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Pet'),
            preserve_default=False,
        ),
    ]
