# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171029_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeio',
            name='idRecorrencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Passeio'),
        ),
    ]
