# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passeio_recorrencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passeio',
            name='recorrencias',
        ),
    ]
