# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:24
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_passeio_recorrencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='recorrencias',
            field=recurrence.fields.RecurrenceField(default=None, blank=True, null=True),
            preserve_default=False,
        ),
    ]
