# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:32
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_passeio_recorrencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeio',
            name='recorrencias',
            field=recurrence.fields.RecurrenceField(blank=True, default=None, null=True),
        ),
    ]
