# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171029_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPasseio', models.CharField(choices=[(b'P', b'Passeio'), (b'B', b'Banho'), (b'V', b'Veterinario'), (b'T', b'Treinamento')], max_length=1)),
                ('passeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Passeador')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipousuario',
        ),
    ]
