# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171203_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='passeador',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipousuario',
            field=models.ManyToManyField(to='api.TipoUsuario'),
        ),
    ]
