# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171203_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='passeador',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Passeador'),
        ),
    ]
