# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171205_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.DateField(blank=True),
        ),
    ]
