# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171205_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
    ]
