# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 05:19
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171029_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='recorrencias',
            field=recurrence.fields.RecurrenceField(default=''),
            preserve_default=False,
        ),
    ]
